### ISSUE TITLE
Match between runs

### ISSUE THREAD

**Issue by andrewjmc** [fickludd/dinosaur#11]
Hello,

Is Dinosaur able to match features between samples, or would this need further processing?

Thanks,

Andrew

**Comment by flevander** [comment]
Hello Andrew

Dinosaur only performs feature detection. Matching between runs (alignment) has to be done separately. 

Best regards

Fredrik

**Comment by andrewjmc** [comment]
Thanks Fredrik. In the meantime, searching for citing articles has led me to Quandenser which uses Dinosaur and does spectral clustering and MBR, which is just what I was looking for!

Best wishes,

Andrew

**Comment by andrewjmc** [comment]
Sorry if this is clear in the paper, but I couldn't fully convince myself... does Dinosaur by default cluster differently charged species with the same RT and mass?

**Comment by flevander** [comment]
There is no built-in clustering of differently charged species that could originate from the same molecule (Similar RT and mass), so also such clustering has to be done by external algorithms.

**Comment by andrewjmc** [comment]
Thanks,

Andrew
