### ISSUE TITLE
Maven error when compiled as dependency within Quandenser

### ISSUE THREAD

**Issue by andrewjmc** [fickludd/dinosaur#12]
I am trying to compile Quandenser which pulls Dinosaur as a dependency. I get an error:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Dinosaur 1.1.3
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/net/alchim31/maven/maven-scala-plugin/2.15.2/maven-scala-plugin-2.15.2.pom
[WARNING] The POM for net.alchim31.maven:maven-scala-plugin:jar:2.15.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.764s
[INFO] Finished at: Wed Nov 20 15:11:37 GMT 2019
[INFO] Final Memory: 22M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin net.alchim31.maven:maven-scala-plugin:2.15.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.alchim31.maven:maven-scala-plugin:jar:2.15.2: Could not find artifact net.alchim31.maven:maven-scala-plugin:pom:2.15.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

It might be the same issue as #10, but difficult to tell. This appears to be because scala-tools.org does not exist any more. When I changed the following lines...

```      <plugin>
        <groupId>org.scala-tools</groupId>
        <artifactId>maven-scala-plugin</artifactId>
        <version>2.15.2</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <scalaVersion>${scala.version}</scalaVersion>
        </configuration>
      </plugin>
```

such that groupId became `net.alchim31.maven` as per https://davidb.github.io/scala-maven-plugin/usage.html, it still fails as the specific version (2.15.2) is not found there.

Should I use a newer version, or do you know of a better alternative repository?

Thanks,

Andrew

**Comment by andrewjmc** [comment]
I'ver tried to remove the dependency upon scala-tools.org, but it seems it's present in other immun.lth.se modules (Xml, etc). I suspect these are all part of your (or your organisation's) ecosystem. Do you have any ideas how this can be updated?

**Comment by andrewjmc** [comment]
I can see them all here: https://mvnrepository.com/artifact/se.lth.immun

**Comment by flevander** [comment]
Hi Andrew,

Sorry for late feedback. I haven't tested the Quandenser version of Dinosaur, and as it seems to be compiling version 1.1.3 of Dinosaur it is probably not using the latest version, or Matthews fork. 
Do you still get the same issues if you build the current version of Dinosaur? There are some recent version changes in pom.xml, including the one solving issue #10 , so maybe these solves the issues you are seeing. At least it builds directly using a fresh Maven install on Mac OSX with OpenJDK 13.0.1, retrieving all dependencies without problem.

Regards 

Fredrik

.

**Comment by andrewjmc** [comment]
Thanks for the suggestion Fredrik. For the moment I've fallen back on using precompiled Quandenser on Windows (compilation needed for Linux as distributed as package which can't be installed without root). I'll try and give the latest dinosaur a go, but unsure if it can be directly plugged into quandenser (quandenser relies upon targeted mode).

**Comment by flevander** [comment]
Closing this issue, as not relevant for the version hosted here anymore.
