### ISSUE TITLE
IntensitySum

### ISSUE THREAD

**Issue by andrewjmc** [fickludd/dinosaur#13]
Is the intensity sum a simple sim (i.e. will vary depending upon MS1 frequency), or is it an area under the curve statistic based on a fitted curve? I scanned the paper but could not tell.

Thanks,

Andrew

**Comment by fickludd** [comment]
Hi @andrewjmc,

The intensity is a simple sum over the matched centroids from the scans. Happens here: https://github.com/fickludd/dinosaur/blob/master/src/main/scala/se/lth/immun/Hill.scala#L184.

**Comment by andrewjmc** [comment]
Thanks
