### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by lorenzgerber** [fickludd/dinosaur#2]
Hi, thanks for a great piece of software. 
I was wondering if there is somewhere an example/documentation of how to use the 'target' mode?
Lorenz

**Comment by fickludd** [comment]
Hi Lorenz, and thanks!

There is not so much information on the target mode, as it was a research track we started exploring but never really verified as other projects got higher priority. As I remember it, the target mode is essentially usable but unrefined, meaning that some healthy caution and evaluation is recommended, if you get it to work =).

**Comment by lorenzgerber** [comment]
Hi Johan, 
Sorry, I forgot to close the issue, I got it actually working nicely. Cheers from Umeå
