### ISSUE TITLE
Low performance for Orbitrap Fusion data

### ISSUE THREAD

**Issue by markmipt** [fickludd/dinosaur#4]
Hi guys,
I've processed a lot of data using the dinosaur and it works fine for Elite, QExactive and Velos Orbitrap data. Hovewer, there are an extremely low number of detected peptide features for Orbitrap Fusion data (I've tried multiple data sets from several several studies on ProteomeXChange) using the same (almost default one) dinosaur parameters. Have you noticed such behaviour?

Regards,
Mark

**Comment by flevander** [comment]
Hi Mark

It has been working just fine with the fusion data we used it on. Could you point us to a datafile where performance has been bad? Is the data collected in profile mode? Target value for MS1 resolution?

Regards

Fredrik

**Comment by markmipt** [comment]
The data was collected in centroid mode. MS1 resolution is 120k. The dinosaur reports only 7000 peptide features, while the MS/MS search for this data reports 19000 peptides at 1% FDR. All datafiles (raw, mzML generated using msconvert, dinosaur input settings and output results, as well as MS/MS search output) are available at http://pubdata.theorchromo.ru/fusiontest/

Best regards,
Mark

**Comment by flevander** [comment]
It seems like the settings used for conversion to centroid data using msconvert somehow lead to the low number of detected features. I reconverted the RAW to mzML.gz (msconvert version 3.0.10386 with -n and -g options), and Dinosaur extracts more than 100000 features from the generated file, both with your advanced param settings and using default parameters (130000 features with default params). 

I then converted the RAW again after also adding --filter "peakPicking true 1-" to the msconvert conversion, thus generating centroid data (and a convenient file size of 131 MB, compared to the 869 MB raw). The result is similar to the previous one, with 126000 features extracted with default params. I haven't looked closer into the centroid mzML file you provided, but apparently the centroiding or some other filter has not worked optimally. Maybe it is just the old version of msconvert 3.0.5533. So please test if just reconverting to mzML with a newer version of msconvert works at your side as well.

**Comment by markmipt** [comment]
Fredrik, thank you very much for your help! As you said, the problem was in msconvert. Using mzml file converted using the latest msconvert version (3.0.11417), the dinosaur reports 100k+ features.

P.S. Thank your team for the great software! We use it in our MS1 search engine (http://pubs.acs.org/doi/abs/10.1021/acs.jproteome.7b00365) and it works better than other  peak picking tools we have tried (OpenMS, Hardklor and mMass)

Regards,
Mark
