### ISSUE TITLE
DIA data will work?

### ISSUE THREAD

**Issue by heejongkim** [fickludd/dinosaur#7]
Hi,

Have you guys tried with DIA data with Dinosaur?

thanks,

hee jong kim

**Comment by markmipt** [comment]
Hi,

I've processed DIA data from (doi: 10.1016/j.jprot.2017.12.014) recently and the results of my workflow were similar to any other DDA data I processed before.

I believe that there will be no difference between DDA and DIA processing when MS1 spectra are recorded quite often (at least one MS1 scan per few seconds)

P.S. I'm user, not a developer

Regards,
Mark

**Comment by heejongkim** [comment]
@markmipt Thank you so much!
I guess I should give it a shot and come back with the result.
If you don't mind, can you tell me a little bit more about your DIA workflow, such as what tools are tangled together to generate what kind of results?

best,
hee jong

**Comment by markmipt** [comment]
I'm using it with my MS1-based search engine (https://bitbucket.org/markmipt/ms1searchpy). So, I identify and quantify proteins using peptide features generated by Dinosaur from mzML files. So, in terms of number of identified peptides/proteins and quantitation results it seems that everything OK with DIA

**Comment by heejongkim** [comment]
haha. I was literally looking at your paper without knowing I'm talking to the author. Glad to have an intimate conversation with you. I will give a shot and get back to you soon. Thanks. :)

**Comment by markmipt** [comment]
You can write me directly at markmipt@gmail.com regarding my paper/software

**Comment by fickludd** [comment]
@heejongkim It was some time ago now, but I'm pretty certain we processed QExactive DIA data using Dinosaur during development. Unclear how it will fare with TrippleTOF data, I guess you would just run, look at the report plots, and tweak parameters. Nowadays @markmipt probably know better how it works than me :).
